replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/prime-sign-387921/nodejs
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"


ingress:
  enabled: true
  annotations: 
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true" 
  hosts:
    - host: nodejsqa.topeda.link
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: nodejsqa-tls
      hosts:
        - nodejsqa.topeda.link